name: pet_pal_health
description: "Pet Pal Health - A mobile-first pet health tracking app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  supabase_flutter: ^2.0.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  google_fonts: ^8.0.1
  flutter_local_notifications: ^20.1.0
  intl: ^0.20.2
  go_router: ^17.1.0
  flutter_dotenv: ^6.0.0
  logger: ^2.0.2
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  flex_color_scheme: ^8.4.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.7.0
  pdf: ^3.11.1
  printing: ^5.13.2
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  shared_preferences: ^2.5.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default:21


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo_illustration.png
    - assets/images/app_icon.png

dependency_overrides:
  sqflite_android: 2.4.1


